paths:
  # model_dir: "/tahoe/data/ckpts/TahoeX1/mosaicfm-70m-merged"
  hf_repo_id: "tahoebio/Tahoe-x1"
  hf_model_size: "70m"
  adata_input: "/tahoe/data/datasets/benchmark/kim2020_lung/kim_test.h5ad" #"/tahoe/data/datasets/benchmark/CCLE/ccle.h5ad" # "/tahoe/data/datasets/benchmark/tahoe/Tahoe50k_train.h5ad"
  adata_output: "./pred_adata.h5ad"
  drug_to_id_path: "drug_to_id_pad.json"
  drug_fps_path: "drug_fps_pad.npy"
  model_name: "Tahoe-x1"
  # gene_output: "./gene_output.npz"
data:
  cell_type_key: "cell_type" #"OncotreeLineage"
  gene_id_key: "ensembl_id" #"feature_id"
predict:
  batch_size: 64
  seq_len_dataset: 2048 #8192
  num_workers: 8
  prefetch_factor: 48 #2
  return_gene_embeddings: False  # Whether to extract gene embeddings
  use_chem_inf: False  # Whether to use chemical information for prediction if the model is trained with chemical information
